#!/usr/bin/env python3
"""Filter 0514 query-event annotations for exp3.

Inputs are the canonical query-event files generated by
build_query_event_annotations.py. The script writes new annotations beside each
dataset without modifying either original annotations.jsonl or query_events.jsonl.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import re
from collections import Counter
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any


DEFAULT_DATASET2_ROOT = Path("/mmu_mllm_hdd/zhouhanshu/test/exp3/streamweave_v5/dataset2")
STREAMO_NAME = "Streamo-Instruct-465K"
COGSTREAM_NAME = "CogStream"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset2-root", type=Path, default=DEFAULT_DATASET2_ROOT)
    parser.add_argument("--streamo-name", default=STREAMO_NAME)
    parser.add_argument("--cogstream-name", default=COGSTREAM_NAME)
    parser.add_argument("--input", default="query_events.jsonl")
    parser.add_argument("--output", default="query_events_0514_filtered.jsonl")
    parser.add_argument("--summary-suffix", default=".summary.json")
    parser.add_argument("--min-video-seconds", type=float, default=20.0)
    parser.add_argument("--max-video-seconds", type=float, default=110.0)
    parser.add_argument("--min-answer-gap-seconds", type=float, default=7.0)
    parser.add_argument("--max-frame-tail-seconds", type=float, default=3.0)
    parser.add_argument("--skip-streamo", action="store_true")
    parser.add_argument("--skip-cogstream", action="store_true")
    return parser.parse_args()


def read_jsonl(path: Path) -> Iterable[dict[str, Any]]:
    with path.open(encoding="utf-8") as handle:
        for line_index, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            value = json.loads(line)
            if not isinstance(value, dict):
                raise ValueError(f"{path}:{line_index} is not a JSON object")
            yield value


def write_jsonl(path: Path, rows: Iterable[Mapping[str, Any]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
            count += 1
    return count


def write_json(path: Path, data: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def coerce_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return float(default)


def coerce_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return int(default)


def round_time_to_fps(value: Any, fps: float) -> float:
    timestamp = coerce_float(value, 0.0)
    if fps <= 0:
        fps = 1.0
    return math.floor(timestamp * fps + 0.5) / fps


def normalize_event_times_to_fps(row: dict[str, Any]) -> dict[str, Any]:
    fps = coerce_float(row.get("sample_fps"), 1.0)
    if fps <= 0:
        fps = 1.0
    query_events = row.get("query_events")
    if not isinstance(query_events, list):
        return row
    for query_event in query_events:
        if not isinstance(query_event, dict):
            continue
        if query_event.get("time") is not None:
            query_event["time"] = round_time_to_fps(query_event.get("time"), fps)
        answer_events = query_event.get("answer_events")
        if not isinstance(answer_events, list):
            continue
        for answer_event in answer_events:
            if not isinstance(answer_event, dict):
                continue
            for key in ("time", "evidence_time"):
                if answer_event.get(key) is not None:
                    answer_event[key] = round_time_to_fps(answer_event.get(key), fps)
    return row


def normalize_option_text(value: Any) -> str:
    text = str(value or "").strip().casefold()
    text = re.sub(r"^[a-z]\.\s*", "", text)
    return re.sub(r"\s+", " ", text)


def has_duplicate_options(row: Mapping[str, Any]) -> bool:
    query_events = row.get("query_events")
    if not isinstance(query_events, list):
        return False
    for query_event in query_events:
        if not isinstance(query_event, Mapping):
            continue
        options = query_event.get("options")
        if not isinstance(options, list) or not options:
            continue
        normalized = [normalize_option_text(option) for option in options]
        if len(set(normalized)) != len(normalized):
            return True
    return False


def declared_video_seconds(row: Mapping[str, Any]) -> float:
    fps = coerce_float(row.get("sample_fps"), 1.0)
    if fps <= 0:
        fps = 1.0
    frame_count = coerce_int(row.get("frame_count"), 0)
    if frame_count > 0:
        return frame_count / fps
    return coerce_float(row.get("realtime", row.get("duration")), 0.0)


def sorted_answer_events(query_event: Mapping[str, Any]) -> list[dict[str, Any]]:
    answer_events = query_event.get("answer_events")
    if not isinstance(answer_events, list):
        return []
    out = [dict(event) for event in answer_events if isinstance(event, dict)]
    return sorted(out, key=lambda item: (coerce_float(item.get("time"), 0.0), str(item.get("content") or "")))


def all_answer_times(row: Mapping[str, Any]) -> list[float]:
    times: list[float] = []
    query_events = row.get("query_events")
    if not isinstance(query_events, list):
        return times
    for query_event in query_events:
        if not isinstance(query_event, Mapping):
            continue
        for answer_event in sorted_answer_events(query_event):
            times.append(coerce_float(answer_event.get("time"), 0.0))
    return sorted(times)


def first_query_time(row: Mapping[str, Any]) -> float | None:
    query_events = row.get("query_events")
    if not isinstance(query_events, list) or not query_events:
        return None
    times = [
        coerce_float(query_event.get("time"), 0.0)
        for query_event in query_events
        if isinstance(query_event, Mapping)
    ]
    if not times:
        return None
    return min(times)


def min_adjacent_answer_gap(row: Mapping[str, Any]) -> float | None:
    query_events = row.get("query_events")
    if not isinstance(query_events, list):
        return None
    min_gap: float | None = None
    for query_event in query_events:
        if not isinstance(query_event, Mapping):
            continue
        times = [coerce_float(event.get("time"), 0.0) for event in sorted_answer_events(query_event)]
        for prev, cur in zip(times, times[1:]):
            gap = cur - prev
            if min_gap is None or gap < min_gap:
                min_gap = gap
    return min_gap


def answer_count_distribution(rows: Iterable[Mapping[str, Any]]) -> dict[str, int]:
    counter: Counter[int] = Counter()
    for row in rows:
        query_events = row.get("query_events")
        if not isinstance(query_events, list):
            continue
        for query_event in query_events:
            if not isinstance(query_event, Mapping):
                continue
            counter[len(sorted_answer_events(query_event))] += 1
    return {str(key): counter[key] for key in sorted(counter)}


def duration_bins(rows: Iterable[Mapping[str, Any]]) -> dict[str, int]:
    bins = [
        (0, 20, "[0,20)"),
        (20, 40, "[20,40)"),
        (40, 60, "[40,60)"),
        (60, 80, "[60,80)"),
        (80, 100, "[80,100)"),
        (100, 110.000001, "[100,110]"),
        (110.000001, math.inf, ">110"),
    ]
    counter: Counter[str] = Counter()
    for row in rows:
        seconds = declared_video_seconds(row)
        for lower, upper, label in bins:
            if lower <= seconds < upper:
                counter[label] += 1
                break
    return {label: counter[label] for _lower, _upper, label in bins}


def collect_category_counts(rows: Iterable[Mapping[str, Any]]) -> dict[str, dict[str, int]]:
    counters: dict[str, Counter[str]] = {
        "split_counts": Counter(),
        "task_counts": Counter(),
        "task_family_counts": Counter(),
        "source_dataset_counts": Counter(),
        "query_type_counts": Counter(),
        "answer_policy_counts": Counter(),
    }
    for row in rows:
        for field, counter_name in (
            ("split", "split_counts"),
            ("task", "task_counts"),
            ("task_family", "task_family_counts"),
            ("source_dataset", "source_dataset_counts"),
        ):
            counters[counter_name][str(row.get(field) or "")] += 1
        query_events = row.get("query_events")
        if isinstance(query_events, list):
            for query_event in query_events:
                if not isinstance(query_event, Mapping):
                    continue
                counters["query_type_counts"][str(query_event.get("query_type") or "")] += 1
                counters["answer_policy_counts"][str(query_event.get("answer_policy") or "")] += 1
    return {name: dict(counter.most_common()) for name, counter in counters.items()}


def frame_alignment_ok(row: Mapping[str, Any], *, max_tail_seconds: float) -> bool:
    answer_times = all_answer_times(row)
    if not answer_times:
        return False
    final_answer_time = max(answer_times)
    frame_count = coerce_float(row.get("frame_count"), 0.0)
    tail = frame_count - final_answer_time
    return 0.0 <= tail <= max_tail_seconds + 1e-6


def set_declared_end(row: dict[str, Any], final_answer_time: float) -> None:
    frame_count = max(1, int(math.ceil(final_answer_time - 1e-9)))
    row["frame_count"] = frame_count
    row["realtime"] = float(final_answer_time)
    if "duration" in row:
        row["duration"] = float(final_answer_time)
    if "input_window_end" in row:
        row["input_window_end"] = frame_count
    if "input_window_end_seconds" in row:
        row["input_window_end_seconds"] = float(final_answer_time)


def filter_row(
    source_row: Mapping[str, Any],
    *,
    min_video_seconds: float,
    max_video_seconds: float,
    min_answer_gap_seconds: float,
    max_frame_tail_seconds: float,
) -> tuple[dict[str, Any] | None, str, dict[str, Any]]:
    row = normalize_event_times_to_fps(copy.deepcopy(dict(source_row)))
    query_events = row.get("query_events")
    if not isinstance(query_events, list) or not query_events:
        return None, "missing_query_events", {}
    if has_duplicate_options(row):
        return None, "duplicate_options", {}

    query_time = first_query_time(row)
    if query_time is None:
        return None, "missing_query_time", {}

    original_answer_times = all_answer_times(row)
    if not original_answer_times:
        return None, "missing_answer_events", {}

    original_video_seconds = declared_video_seconds(row)
    if original_video_seconds < min_video_seconds:
        return None, "original_video_too_short", {"original_video_seconds": original_video_seconds}

    original_first_answer_time = original_answer_times[0]
    should_truncate = original_video_seconds > max_video_seconds
    if should_truncate and query_time > max_video_seconds:
        return None, "query_after_max_cutoff", {
            "query_time": query_time,
            "original_video_seconds": original_video_seconds,
        }
    if should_truncate and original_first_answer_time > max_video_seconds:
        return None, "first_answer_after_max_cutoff", {
            "first_answer_time": original_first_answer_time,
            "original_video_seconds": original_video_seconds,
        }

    retained_answer_count = 0
    removed_answer_count = 0
    retained_query_events: list[dict[str, Any]] = []
    for query_event in query_events:
        if not isinstance(query_event, Mapping):
            continue
        event = copy.deepcopy(dict(query_event))
        answers = sorted_answer_events(event)
        if should_truncate:
            retained_answers = [
                answer
                for answer in answers
                if coerce_float(answer.get("time"), 0.0) <= max_video_seconds
            ]
        else:
            retained_answers = answers
        removed_answer_count += len(answers) - len(retained_answers)
        if not retained_answers:
            continue
        event["answer_events"] = retained_answers
        retained_answer_count += len(retained_answers)
        retained_query_events.append(event)

    if not retained_query_events:
        return None, "no_answers_before_cutoff", {
            "removed_answer_events": removed_answer_count,
            "original_video_seconds": original_video_seconds,
        }

    row["query_events"] = retained_query_events
    gap = min_adjacent_answer_gap(row)
    if gap is not None and gap < min_answer_gap_seconds - 1e-6:
        return None, "answer_gap_too_small", {
            "min_answer_gap": gap,
            "original_video_seconds": original_video_seconds,
            "truncated": should_truncate,
        }

    final_answer_time = max(all_answer_times(row))
    set_declared_end(row, final_answer_time)
    final_video_seconds = declared_video_seconds(row)
    if final_video_seconds < min_video_seconds:
        return None, "final_video_too_short", {
            "final_video_seconds": final_video_seconds,
            "final_answer_time": final_answer_time,
        }
    if final_video_seconds > max_video_seconds:
        return None, "final_video_too_long", {
            "final_video_seconds": final_video_seconds,
            "final_answer_time": final_answer_time,
        }
    if not frame_alignment_ok(row, max_tail_seconds=max_frame_tail_seconds):
        return None, "final_frame_not_aligned", {
            "frame_count": row.get("frame_count"),
            "final_answer_time": final_answer_time,
        }

    row["filter_0514"] = {
        "source_file": str(source_row.get("dataset") or ""),
        "min_video_seconds": min_video_seconds,
        "max_video_seconds": max_video_seconds,
        "min_answer_gap_seconds": min_answer_gap_seconds,
        "max_frame_tail_seconds": max_frame_tail_seconds,
        "original_frame_count": source_row.get("frame_count"),
        "original_realtime": source_row.get("realtime"),
        "original_duration": source_row.get("duration"),
        "original_video_seconds_by_frame_count": original_video_seconds,
        "truncated_from_over_max": should_truncate,
        "removed_answer_events_after_max": removed_answer_count,
        "retained_answer_events": retained_answer_count,
        "final_answer_time": final_answer_time,
        "final_frame_count": row.get("frame_count"),
    }
    return row, "kept", {
        "truncated": should_truncate,
        "removed_answer_events": removed_answer_count,
        "original_video_seconds": original_video_seconds,
        "final_video_seconds": final_video_seconds,
    }


def filter_dataset(
    dataset_dir: Path,
    *,
    input_name: str,
    output_name: str,
    summary_suffix: str,
    min_video_seconds: float,
    max_video_seconds: float,
    min_answer_gap_seconds: float,
    max_frame_tail_seconds: float,
) -> dict[str, Any]:
    input_path = dataset_dir / input_name
    output_path = dataset_dir / output_name
    rows = list(read_jsonl(input_path))
    kept_rows: list[dict[str, Any]] = []
    reason_counts: Counter[str] = Counter()
    truncated_rows = 0
    removed_answers_by_truncation = 0
    original_duration_bins = duration_bins(rows)

    for source_row in rows:
        filtered_row, reason, info = filter_row(
            source_row,
            min_video_seconds=min_video_seconds,
            max_video_seconds=max_video_seconds,
            min_answer_gap_seconds=min_answer_gap_seconds,
            max_frame_tail_seconds=max_frame_tail_seconds,
        )
        reason_counts[reason] += 1
        if filtered_row is None:
            continue
        kept_rows.append(filtered_row)
        if info.get("truncated"):
            truncated_rows += 1
        removed_answers_by_truncation += int(info.get("removed_answer_events") or 0)

    written = write_jsonl(output_path, kept_rows)
    summary: dict[str, Any] = {
        "dataset": dataset_dir.name,
        "source_path": str(input_path),
        "output_path": str(output_path),
        "input_rows": len(rows),
        "written_rows": written,
        "dropped_rows": len(rows) - written,
        "filter_reason_counts": dict(reason_counts.most_common()),
        "truncated_rows": truncated_rows,
        "removed_answer_events_by_truncation": removed_answers_by_truncation,
        "rules": {
            "min_video_seconds": min_video_seconds,
            "max_video_seconds": max_video_seconds,
            "min_answer_gap_seconds": min_answer_gap_seconds,
            "max_frame_tail_seconds": max_frame_tail_seconds,
            "event_time_rounding": "round half up to sample_fps before filtering",
            "duplicate_options": "drop rows whose normalized options contain duplicates",
            "duration_field": "frame_count / sample_fps",
            "final_frame_count": "ceil(last retained answer time)",
        },
        "input_answer_event_count_distribution": answer_count_distribution(rows),
        "output_answer_event_count_distribution": answer_count_distribution(kept_rows),
        "input_duration_bins_by_frame_count": original_duration_bins,
        "output_duration_bins_by_frame_count": duration_bins(kept_rows),
        **collect_category_counts(kept_rows),
    }
    write_json(output_path.with_suffix(output_path.suffix + summary_suffix), summary)
    return summary


def main() -> None:
    args = parse_args()
    summaries = []
    if not args.skip_streamo:
        summaries.append(
            filter_dataset(
                args.dataset2_root / args.streamo_name,
                input_name=args.input,
                output_name=args.output,
                summary_suffix=args.summary_suffix,
                min_video_seconds=args.min_video_seconds,
                max_video_seconds=args.max_video_seconds,
                min_answer_gap_seconds=args.min_answer_gap_seconds,
                max_frame_tail_seconds=args.max_frame_tail_seconds,
            )
        )
    if not args.skip_cogstream:
        summaries.append(
            filter_dataset(
                args.dataset2_root / args.cogstream_name,
                input_name=args.input,
                output_name=args.output,
                summary_suffix=args.summary_suffix,
                min_video_seconds=args.min_video_seconds,
                max_video_seconds=args.max_video_seconds,
                min_answer_gap_seconds=args.min_answer_gap_seconds,
                max_frame_tail_seconds=args.max_frame_tail_seconds,
            )
        )
    for summary in summaries:
        print(f"Wrote {summary['written_rows']} rows to {summary['output_path']}")


if __name__ == "__main__":
    main()
