### model
model_name_or_path: /mmu_mllm_hdd/Models/Qwen3-VL-8B-Instruct
image_max_pixels: 131072
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: true
freeze_multi_modal_projector: true

### dataset
dataset: streamweave_sft
dataset_dir: data_streamweave
media_dir: /mmu_mllm_hdd/zhouhanshu/test/exp2/streamweave_v4/dataset/streamweave_data
template: qwen3_vl_nothink
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-vl-8b/lora/streamweave_sft
logging_steps: 1
save_steps: 20
save_total_limit: 3
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null
